on: [push]
name: Tests
jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: go test ./... -race
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
